name: Manual Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create GitHub Release'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          
      - name: Build React app
        run: npm run build
        
      - name: Build Electron app
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BeastBrowser-Windows
          path: build-output/*.exe
          retention-days: 30
          
      - name: Get package version
        id: package-version
        run: |
          $version = node -p "require('./package.json').version"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          
      - name: Create Release
        if: github.event.inputs.create_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: build-output/*.exe
          tag_name: v${{ steps.package-version.outputs.VERSION }}
          name: BeastBrowser v${{ steps.package-version.outputs.VERSION }}
          body: |
            ## 🚀 BeastBrowser v${{ steps.package-version.outputs.VERSION }}
            
            ### What's New
            - Complete blue-indigo professional theme
            - Support for all platforms (Windows, macOS, Linux, Android, iOS, TV)
            - Smart profile naming with auto-increment
            - Auto pagination for better UX
            - Parallel profile launching (60-70% faster)
            - Enhanced anti-detection features
            - Full proxy support
            
            ### Download
            Download the installer below and run it on Windows 10/11 (64-bit)
            
            ### Features
            ✅ Anti-Detection Browser
            ✅ Proxy Management (HTTP/HTTPS/SOCKS5)
            ✅ Profile Management
            ✅ Browser Automation (RPA)
            ✅ Fingerprint Randomization
            ✅ Timezone Auto-Detection
            
            ---
            Built with ❤️ by BeastBrowser Team
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
